version: "3.8"

services:
  jobmanager:
    image: flink:latest
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /home/ubuntu/flink-consumer:/flink-consumer

  taskmanager:
    image: flink:latest
    scale: 2
    container_name: taskmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  flink-consumer:
    image: flink-consumer
    container_name: flink-consumer
    depends_on:
      - jobmanager
    volumes:
      - /home/ubuntu/flink-consumer:/app
